export enum TransactionType {
  INCOME = 'INCOME', // Others gave me (+)
  EXPENSE = 'EXPENSE' // I gave others (-)
}

export interface Expense {
  id: string; // Unique ID (generated by App or Sheet)
  timestamp: string;
  date: string; // YYYY-MM-DD
  day: string; // Monday, Tuesday...
  category: string;
  item: string;
  type: TransactionType;
  amount: number;
  currency: string;
  payer: string; // Who paid
  personalNote?: string;
  settled: boolean;
  remark?: string;
  exchangeRate: number;
}

export interface AppConfig {
  gasUrl: string;
  allowedEmails: string[];
  googleClientId?: string;
  baseCurrency: string;
}

export interface User {
  email: string;
  name: string;
  picture?: string;
}

export interface ApiState {
  isLoading: boolean;
  error: string | null;
  lastUpdated: number | null;
}
